#!/bin/bash

read -r POST_STRING
#POST : change_to_pdu with raw-data : device_name => curl "http://localhost/function" --data-raw "change_to_pdu <AT_device_name>"
change_to_pdu() {
  local device_name="$1"
  echo -e "leano_serial AT+CPMS='"ME"','"ME"','"ME"'\r\n" > "/dev/$device_name" && timeout 0.5 cat "/dev/$device_name"
  echo -e "leano_serial AT+CPMS='"SM"','"SM"','"SM"'\r\n" > "/dev/$device_name" && timeout 0.5 cat "/dev/$device_name"
  echo -e "AT+CMGF=0\r\n" > "/dev/$device_name" && timeout 0.5 cat "/dev/$device_name"
}
#POST : change_to_pdu with raw-data : creat_sms_list => curl "http://localhost/function" --data-raw "creat_sms_list <AT_device_name> <0 OR 1 for delete all SMS After save>"
creat_sms_list() {
  local device_name="$1"
  local delete_sms="$2"
  local countsms
  local countsms_SE

  countsms=$(tail -n 1 smslist | cut -d ":" -f1)
  countsms_SE=$(echo -e "leano_serial AT+CPMS?\r\n" > "/dev/$device_name" && timeout 0.5 cat "/dev/$device_name" | sed -n '2 p' | cut -d',' -f2)

  if [ -z "$countsms" ]; then
    countsms=0
  fi

  if [ "$countsms_SE" -gt 0 ]; then
    for i in $(seq 0 "$countsms_SE"); do
      countsms=$((countsms + 1))
      checksender=$(leano_serial AT+CMGR="$i" | sed -n '3p')
      pdu=$(echo -e "leano_serial AT+CPMS=$i\r\n" > "/dev/$device_name" && timeout 0.5 cat "/dev/$device_name")

      if [ -z "$pdu" ]; then
        continue
      fi

      echo "L$countsms:$pdu" >> smslist
    done

    if [ "$delete_sms" == 1 ]; then
      echo -e "leano_serial AT+CMGD=1,4\r\n" > "/dev/$device_name" && timeout 0.5 cat "/dev/$device_name"
    fi
  fi
}
#POST : change_to_pdu with raw-data : json_sms_pdu_list => curl "http://localhost/function" --data-raw "json_sms_pdu_list"
json_sms_pdu_list() {
  local last_line
  local all_lines
  local loopcount

  last_line=$(tail -n 1 smslist)
  all_lines=$(wc -l < smslist)
  loopcount=0

  echo "{"
  echo '"lenghtt":"'$all_lines'",'

  if [ "$all_lines" -eq 0 ]; then
    echo '"lenghtt":"'$all_lines'"'
  else
    echo '"lenghtt":"'$all_lines'",'
  fi

  while IFS= read -r line; do
    loopcount=$((loopcount + 1))
    data=$(grep "L$loopcount:" <<< "$line" | cut -d ':' -f2 | tr -d '\r')
    id=$(grep "$loopcount:" <<< "$line" | cut -d ':' -f1)

    if [ "$last_line" == "$line" ]; then
      echo '"ID'$loopcount'":"'$id'",'
      echo '"DATA'$loopcount'":"'$data'"'
    else
      echo '"ID'$loopcount'":"'$id'",'
      echo '"DATA'$loopcount'":"'$data'",'
    fi
  done < smslist

  echo "}"
}
#ipremote=`echo $HTTP_REFERER | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
if type "$POST_STRING" &>/dev/null && grep -q 'function' <<< "$POST_STRING"; then
  $POST_STRING
else
  json='{"status":"error","code":"401","message":"shell command WTF?:)))"}'
  echo ""
  echo "$json"
fi


